version: "2"

volumes:
  nginx_conf: {}
  nginx_vhost: {}
  nginx_html: {}
  nginx_certs: {}

services:
  nginxproxy:
    image: jwilder/nginx-proxy
    container_name: nginxproxy_production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs
      - nginx_html:/usr/share/nginx/html
    networks:
      - nginxproxy_network

  sslgenerator:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: sslgenerator_production
    volumes_from:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginxproxy_network

networks:
  nginxproxy_network:
    name: nginxproxy_network
